name: Fonobus Scheduler

on:
  schedule:
    # Argentina UTC-3
    # 6:45 / 07:00 / 07:10 / 07:15 ARG
    - cron: "45 9 * * 2-6"
    - cron: "0 10 * * 2-6"
    - cron: "10 10 * * 2-6"
    - cron: "15 10 * * 2-6"

  workflow_dispatch:

jobs:
  run-fonobus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Run bot
        env:
          # Secrets
          FONOBUS_TOKEN: ${{ secrets.FONOBUS_TOKEN }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}

          # Variable de control
          RUN_SCHEDULER: ${{ vars.RUN_SCHEDULER }}

        run: |
          uv run python main.py
